"use strict";
const $=id=>document.getElementById(id);
const el={file:$("file"),drop:$("drop"),convert:$("convert"),error:$("error"),mode:$("mode"),preset:$("preset"),colors:$("colors"),colorsOut:$("colorsOut"),smoothness:$("smoothness"),smoothOut:$("smoothOut"),speckle:$("speckle"),speckleOut:$("speckleOut"),threshold:$("threshold"),thresholdOut:$("thresholdOut"),monoPanel:$("monoPanel"),invert:$("invert"),removeBackground:$("removeBackground"),tolerance:$("tolerance"),toleranceOut:$("toleranceOut"),maxDimension:$("maxDimension"),empty:$("empty"),vector:$("vectorPreview"),raster:$("rasterPreview"),code:$("codePreview"),stats:$("stats"),copy:$("copy"),dataUri:$("dataUri"),download:$("download")};
let file=null,svg="",vectorUrl="",rasterUrl="",tab="vector";
const format=n=>new Intl.NumberFormat().format(n);
function setFile(next){file=next;svg="";el.error.textContent="";el.convert.disabled=!file;if(rasterUrl)URL.revokeObjectURL(rasterUrl);rasterUrl=file?URL.createObjectURL(file):"";el.raster.src=rasterUrl;render();if(file)el.stats.textContent=`${file.name} · ${format(file.size)} bytes`}
function render(){el.empty.hidden=Boolean(file||svg);el.vector.hidden=!(svg&&tab==="vector");el.raster.hidden=!(file&&tab==="raster");el.code.hidden=!(svg&&tab==="code");for(const b of document.querySelectorAll(".tab"))b.classList.toggle("active",b.dataset.tab===tab);for(const b of [el.copy,el.dataUri,el.download])b.disabled=!svg}
for(const event of ["dragenter","dragover"]){el.drop.addEventListener(event,e=>{e.preventDefault();el.drop.classList.add("drag")})}for(const event of ["dragleave","drop"]){el.drop.addEventListener(event,e=>{e.preventDefault();el.drop.classList.remove("drag")})}el.drop.addEventListener("drop",e=>setFile(e.dataTransfer.files[0]));el.file.addEventListener("change",()=>setFile(el.file.files[0]));
function sync(){el.colorsOut.textContent=`${el.colors.value} colors`;el.smoothOut.textContent=el.smoothness.value;el.speckleOut.textContent=`${el.speckle.value} px`;el.thresholdOut.textContent=el.threshold.value;el.toleranceOut.textContent=el.tolerance.value;el.monoPanel.hidden=el.mode.value!=="mono";el.colors.disabled=el.mode.value==="mono"}
for(const control of document.querySelectorAll("select,input[type=range],input[type=checkbox]"))control.addEventListener("input",sync);sync();
document.querySelector(".tabs").addEventListener("click",e=>{const button=e.target.closest(".tab");if(!button)return;tab=button.dataset.tab;render()});
el.convert.addEventListener("click",async()=>{if(!file)return;el.convert.disabled=true;el.convert.classList.add("busy");el.convert.textContent="Tracing…";el.error.textContent="";try{const options={mode:el.mode.value,preset:el.preset.value,colors:Number(el.colors.value),smoothness:Number(el.smoothness.value),speckle:Number(el.speckle.value),threshold:Number(el.threshold.value),invert:el.invert.checked,remove_background:el.removeBackground.checked,background_tolerance:Number(el.tolerance.value),max_dimension:Number(el.maxDimension.value),path_precision:2};const form=new FormData();form.append("image",file,file.name);form.append("options",JSON.stringify(options));const response=await fetch("/api/vectorize",{method:"POST",body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);svg=data.svg;el.code.querySelector("code").textContent=svg;if(vectorUrl)URL.revokeObjectURL(vectorUrl);vectorUrl=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));el.vector.src=vectorUrl;tab="vector";el.stats.textContent=`${data.source_width}×${data.source_height} → ${data.traced_width}×${data.traced_height} · ${format(data.path_count)} paths · ${format(data.output_bytes)} bytes · ${data.elapsed_ms} ms`;render()}catch(error){el.error.textContent=error.message}finally{el.convert.disabled=!file;el.convert.classList.remove("busy");el.convert.textContent="Vectorize image"}});
el.copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(svg);el.copy.textContent="Copied";setTimeout(()=>el.copy.textContent="Copy SVG",900)});el.dataUri.addEventListener("click",async()=>{const uri=`data:image/svg+xml,${encodeURIComponent(svg)}`;await navigator.clipboard.writeText(uri);el.dataUri.textContent="Copied";setTimeout(()=>el.dataUri.textContent="Copy data URI",900)});el.download.addEventListener("click",()=>{const a=document.createElement("a");a.href=vectorUrl;a.download=(file?.name.replace(/\.[^.]+$/,"")||"vector")+".svg";a.click()});
