const $=s=>document.querySelector(s);let file=null,job=null,timer=null,quality='balanced';
const fmt=n=>{if(n==null)return'—';const u=['B','KiB','MiB','GiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?2:0)} ${u[i]}`};
fetch('/api/capabilities').then(r=>r.json()).then(c=>{$('#runtime').textContent=`FFmpeg local · ${c.encoders.length} encoders · disk only`;});
function select(f){file=f;$('#source-preview').src=URL.createObjectURL(f);$('#source-preview').style.display='block';$('#source-meta').textContent=`${f.name} · ${fmt(f.size)}`;$('#run').disabled=false;$('#status').textContent='Ready to compress.';}
$('#file').addEventListener('change',e=>e.target.files[0]&&select(e.target.files[0]));const drop=$('#drop');['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>e.dataTransfer.files[0]&&select(e.dataTransfer.files[0]));
document.querySelectorAll('[data-quality]').forEach(b=>b.addEventListener('click',()=>{quality=b.dataset.quality;document.querySelectorAll('[data-quality]').forEach(x=>x.classList.toggle('active',x===b))}));
$('#codec').addEventListener('change',()=>{if($('#codec').value==='vp9'&&$('#engine').value==='nvenc')$('#engine').value='software'});
$('#run').addEventListener('click',async()=>{if(!file)return;const d=new FormData();d.set('video',file);['codec','engine','width','audio-bitrate','start','end','fps'].forEach(k=>d.set(k.replaceAll('-','_'),$('#'+k).value));d.set('quality',quality);['remove-audio','strip-metadata','faststart'].forEach(k=>d.set(k.replaceAll('-','_'),$('#'+k).checked?'true':'false'));$('#run').disabled=true;$('#stop').disabled=false;$('#status').textContent='Streaming to local workspace…';$('#bar').style.width='1%';const r=await fetch('/api/jobs',{method:'POST',body:d});const x=await r.json();if(!r.ok){fail(x.detail||'Could not start');return}job=x;clearInterval(timer);timer=setInterval(poll,700);poll()});
async function poll(){if(!job)return;const r=await fetch(`/api/jobs/${job.id}`);if(!r.ok)return;job=await r.json();$('#bar').style.width=`${Math.max(1,job.progress*100)}%`;$('#status').textContent={queued:'Queued locally…',running:'FFmpeg is compressing…',complete:'Complete.',failed:job.error,stopped:'Stopped.'}[job.status]||job.status;$('#status').classList.toggle('error',job.status==='failed');$('#log').textContent=job.logs.length?job.logs.join('\n'):'FFmpeg is running quietly.';if(job.before)$('#before').textContent=fmt(job.before.bytes);if(job.after){$('#after').textContent=fmt(job.after.bytes);const p=(1-job.after.bytes/job.before.bytes)*100;$('#saved').textContent=`${p.toFixed(1)}%`;$('#output-preview').src=`/api/jobs/${job.id}/output`;$('#output-preview').style.display='block';$('#download').href=`/api/jobs/${job.id}/output?download=true`;$('#download').classList.remove('disabled')}if(!['queued','running'].includes(job.status)){clearInterval(timer);$('#stop').disabled=true;$('#run').disabled=false}}
$('#stop').addEventListener('click',async()=>{if(job)await fetch(`/api/jobs/${job.id}/stop`,{method:'POST'})});function fail(message){$('#status').textContent=message;$('#status').classList.add('error');$('#stop').disabled=true;$('#run').disabled=false}
